import os

os.system("make clean")
os.system("make")
test_files = os.listdir('./test_cases')
# os.system('mkdir -p token_output')
# os.system('mkdir -p parse_output')
# os.system('mkdir -p ast_output')
# os.system('mkdir -p symtab_output')
os.system('mkdir -p icode_output')
os.system('mkdir -p spim_output')
# os.system('mkdir -p eval_output')

for file in test_files:
	os.system('echo "========================= "' + file + '" =========================="')
	## Run Reference Implementation
	os.system('echo "---- Running reference implementation ... ----"')
	os.system("./sclp  -icode " + "./test_cases/" + file)
	# os.system("mv " + "./test_cases/" + file + ".toks " + "./token_output/" + file + ".toks.sclp")
	# os.system("mv " + "./test_cases/" + file + ".parse.sclp " + "./parse_output/" + file + ".parse.sclp")
	# os.system("mv " + "./test_cases/" + file + ".ast " + "./ast_output/" + file + ".ast.sclp")
	# os.system("mv " + "./test_cases/" + file + ".sym " + "./symtab_output/" + file + ".sym.sclp")
	os.system("mv " + "./test_cases/" + file + ".ic " + "./icode_output/" + file + ".ic.sclp")
	os.system("./sclp " + "./test_cases/" + file)
	os.system("mv " + "./test_cases/" + file + ".spim " + "./spim_output/" + file + ".spim.sclp")
	# os.system("./sclp -eval " + "./test_cases/" + file)
	# os.system("mv " + "./test_cases/" + file + ".eval " + "./eval_output/" + file + ".eval.sclp")
	## Run Test Implementation
	os.system('echo "---- Running test implementation ... ----"')
	os.system("./mysclp -icode " + "./test_cases/" + file)
	# os.system("mv " + "./test_cases/" + file + ".toks " + "./token_output/" + file + ".toks")
	# os.system("mv " + "./test_cases/" + file + ".parse " + "./parse_output/" + file + ".parse")
	# os.system("mv " + "./test_cases/" + file + ".ast " + "./ast_output/" + file + ".ast")
	# os.system("mv " + "./test_cases/" + file + ".sym " + "./symtab_output/" + file + ".sym")
	os.system("mv " + "./test_cases/" + file + ".ic " + "./icode_output/" + file + ".ic")
	os.system("mv " + "./test_cases/" + file + ".spim " + "./spim_output/" + file + ".spim")
	# os.system("./mysclp -eval " + "./test_cases/" + file)
	# os.system("mv " + "./test_cases/" + file + ".eval " + "./eval_output/" + file + ".eval")
	##
	# os.system('echo "Testing tokens output ..."')
	# os.system("diff " + "./token_output/" + file + ".toks " + "./token_output/" + file + ".toks.sclp")
	# os.system('echo "Testing parse output ..."')
	# os.system("diff " + "./parse_output/" + file + ".parse " + "./parse_output/" + file + ".parse.sclp")
	# os.system('echo "Testing ast output ..."')
	# os.system("diff " + "./ast_output/" + file + ".ast " + "./ast_output/" + file + ".ast.sclp")
	# os.system('echo "Testing symtab output ..."')
	# os.system("diff " + "./symtab_output/" + file + ".sym " + "./symtab_output/" + file + ".sym.sclp")
	os.system('echo "Testing icode output ..."')
	os.system("diff " + "./icode_output/" + file + ".ic " + "./icode_output/" + file + ".ic.sclp")
	os.system('echo "Testing spim output ..."')
	os.system("diff " + "./spim_output/" + file + ".spim " + "./spim_output/" + file + ".spim.sclp")
	# os.system('echo "Testing eval output ..."')
	# os.system("diff " + "./eval_output/" + file + ".eval " + "./eval_output/" + file + ".eval.sclp")
	os.system('echo "=================================================================="')
	
